//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG.Client.WCFIISHost.Base_CommonService_W {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="SG.Server.IISHost.Base", ConfigurationName="Base_CommonService_W.CommonService_W")]
    public interface CommonService_W {
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetSystemOrganization", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetSystemOrganizationResponse")]
        byte[] GetSystemOrganization(byte[] validationTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetSystemOrganization", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetSystemOrganizationResponse")]
        System.Threading.Tasks.Task<byte[]> GetSystemOrganizationAsync(byte[] validationTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetSystemDataSet", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetSystemDataSetResponse")]
        byte[] GetSystemDataSet(byte[] validationTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetSystemDataSet", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetSystemDataSetResponse")]
        System.Threading.Tasks.Task<byte[]> GetSystemDataSetAsync(byte[] validationTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetSystemDataSetByOrg", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetSystemDataSetByOrgResponse")]
        byte[] GetSystemDataSetByOrg(byte[] validationTicket, string sOrgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetSystemDataSetByOrg", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetSystemDataSetByOrgResponse")]
        System.Threading.Tasks.Task<byte[]> GetSystemDataSetByOrgAsync(byte[] validationTicket, string sOrgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/SearchLog", ReplyAction="SG.Server.IISHost.Base/CommonService_W/SearchLogResponse")]
        byte[] SearchLog(byte[] loginTicket, string sFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/SearchLog", ReplyAction="SG.Server.IISHost.Base/CommonService_W/SearchLogResponse")]
        System.Threading.Tasks.Task<byte[]> SearchLogAsync(byte[] loginTicket, string sFilter);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/TestConnection", ReplyAction="SG.Server.IISHost.Base/CommonService_W/TestConnectionResponse")]
        bool TestConnection(byte[] validationTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/TestConnection", ReplyAction="SG.Server.IISHost.Base/CommonService_W/TestConnectionResponse")]
        System.Threading.Tasks.Task<bool> TestConnectionAsync(byte[] validationTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/TestConnectionD", ReplyAction="SG.Server.IISHost.Base/CommonService_W/TestConnectionDResponse")]
        bool TestConnectionD(byte[] validationTicket, string dbType, string Server, string database, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/TestConnectionD", ReplyAction="SG.Server.IISHost.Base/CommonService_W/TestConnectionDResponse")]
        System.Threading.Tasks.Task<bool> TestConnectionDAsync(byte[] validationTicket, string dbType, string Server, string database, string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/WriteLogOP", ReplyAction="SG.Server.IISHost.Base/CommonService_W/WriteLogOPResponse")]
        void WriteLogOP(byte[] loginTicket, string sFunID, string sFSubunID, string sFdesc, string sSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/WriteLogOP", ReplyAction="SG.Server.IISHost.Base/CommonService_W/WriteLogOPResponse")]
        System.Threading.Tasks.Task WriteLogOPAsync(byte[] loginTicket, string sFunID, string sFSubunID, string sFdesc, string sSql);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetModules", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetModulesResponse")]
        byte[] GetModules(byte[] loginTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetModules", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetModulesResponse")]
        System.Threading.Tasks.Task<byte[]> GetModulesAsync(byte[] loginTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/WriteLog", ReplyAction="SG.Server.IISHost.Base/CommonService_W/WriteLogResponse")]
        void WriteLog(byte[] loginTicket, string logID, byte[] originalData, byte[] changes, string tableName, string keyFieldName, bool isMaster);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/WriteLog", ReplyAction="SG.Server.IISHost.Base/CommonService_W/WriteLogResponse")]
        System.Threading.Tasks.Task WriteLogAsync(byte[] loginTicket, string logID, byte[] originalData, byte[] changes, string tableName, string keyFieldName, bool isMaster);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/SearchLogData", ReplyAction="SG.Server.IISHost.Base/CommonService_W/SearchLogDataResponse")]
        byte[] SearchLogData(byte[] loginTicket, string logUser, string tableName, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/SearchLogData", ReplyAction="SG.Server.IISHost.Base/CommonService_W/SearchLogDataResponse")]
        System.Threading.Tasks.Task<byte[]> SearchLogDataAsync(byte[] loginTicket, string logUser, string tableName, System.DateTime dateFrom, System.DateTime dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/SaveFieldDef", ReplyAction="SG.Server.IISHost.Base/CommonService_W/SaveFieldDefResponse")]
        bool SaveFieldDef(byte[] loginTicket, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/SaveFieldDef", ReplyAction="SG.Server.IISHost.Base/CommonService_W/SaveFieldDefResponse")]
        System.Threading.Tasks.Task<bool> SaveFieldDefAsync(byte[] loginTicket, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetLogFieldDef", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetLogFieldDefResponse")]
        byte[] GetLogFieldDef(byte[] loginTicket, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetLogFieldDef", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetLogFieldDefResponse")]
        System.Threading.Tasks.Task<byte[]> GetLogFieldDefAsync(byte[] loginTicket, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetTracedFields", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetTracedFieldsResponse")]
        string[] GetTracedFields(byte[] loginTicket, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetTracedFields", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetTracedFieldsResponse")]
        System.Threading.Tasks.Task<string[]> GetTracedFieldsAsync(byte[] loginTicket, string tableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/C_GetTableID", ReplyAction="SG.Server.IISHost.Base/CommonService_W/C_GetTableIDResponse")]
        string C_GetTableID(byte[] loginTicket, string sTableName, string sFieldID);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/C_GetTableID", ReplyAction="SG.Server.IISHost.Base/CommonService_W/C_GetTableIDResponse")]
        System.Threading.Tasks.Task<string> C_GetTableIDAsync(byte[] loginTicket, string sTableName, string sFieldID);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/C_GetTableFieldValue", ReplyAction="SG.Server.IISHost.Base/CommonService_W/C_GetTableFieldValueResponse")]
        string C_GetTableFieldValue(byte[] loginTicket, string sTableName, string sField, string SCon);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/C_GetTableFieldValue", ReplyAction="SG.Server.IISHost.Base/CommonService_W/C_GetTableFieldValueResponse")]
        System.Threading.Tasks.Task<string> C_GetTableFieldValueAsync(byte[] loginTicket, string sTableName, string sField, string SCon);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetSQLServerDbListString", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetSQLServerDbListStringResponse")]
        string GetSQLServerDbListString(byte[] validationTicket, string sServerName, string sUser, string sPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetSQLServerDbListString", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetSQLServerDbListStringResponse")]
        System.Threading.Tasks.Task<string> GetSQLServerDbListStringAsync(byte[] validationTicket, string sServerName, string sUser, string sPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetDBLink", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetDBLinkResponse")]
        byte[] GetDBLink(byte[] loginTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetDBLink", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetDBLinkResponse")]
        System.Threading.Tasks.Task<byte[]> GetDBLinkAsync(byte[] loginTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetDBLinkByID", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetDBLinkByIDResponse")]
        byte[] GetDBLinkByID(byte[] loginTicket, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetDBLinkByID", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetDBLinkByIDResponse")]
        System.Threading.Tasks.Task<byte[]> GetDBLinkByIDAsync(byte[] loginTicket, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/G_GetSystemProfile", ReplyAction="SG.Server.IISHost.Base/CommonService_W/G_GetSystemProfileResponse")]
        byte[] G_GetSystemProfile(byte[] loginTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/G_GetSystemProfile", ReplyAction="SG.Server.IISHost.Base/CommonService_W/G_GetSystemProfileResponse")]
        System.Threading.Tasks.Task<byte[]> G_GetSystemProfileAsync(byte[] loginTicket);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/G_GetSystemProfileVal", ReplyAction="SG.Server.IISHost.Base/CommonService_W/G_GetSystemProfileValResponse")]
        string G_GetSystemProfileVal(byte[] loginTicket, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/G_GetSystemProfileVal", ReplyAction="SG.Server.IISHost.Base/CommonService_W/G_GetSystemProfileValResponse")]
        System.Threading.Tasks.Task<string> G_GetSystemProfileValAsync(byte[] loginTicket, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetAttachedFiles", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetAttachedFilesResponse")]
        byte[] GetAttachedFiles(byte[] loginTicket, string docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/GetAttachedFiles", ReplyAction="SG.Server.IISHost.Base/CommonService_W/GetAttachedFilesResponse")]
        System.Threading.Tasks.Task<byte[]> GetAttachedFilesAsync(byte[] loginTicket, string docID);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/getTable", ReplyAction="SG.Server.IISHost.Base/CommonService_W/getTableResponse")]
        byte[] getTable(byte[] loginTicket, string sTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/getTable", ReplyAction="SG.Server.IISHost.Base/CommonService_W/getTableResponse")]
        System.Threading.Tasks.Task<byte[]> getTableAsync(byte[] loginTicket, string sTable);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/getField", ReplyAction="SG.Server.IISHost.Base/CommonService_W/getFieldResponse")]
        byte[] getField(byte[] loginTicket, string sTableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/getField", ReplyAction="SG.Server.IISHost.Base/CommonService_W/getFieldResponse")]
        System.Threading.Tasks.Task<byte[]> getFieldAsync(byte[] loginTicket, string sTableName);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/getDataTableSQL", ReplyAction="SG.Server.IISHost.Base/CommonService_W/getDataTableSQLResponse")]
        byte[] getDataTableSQL(byte[] loginTicket, string sql);
        
        [System.ServiceModel.OperationContractAttribute(Action="SG.Server.IISHost.Base/CommonService_W/getDataTableSQL", ReplyAction="SG.Server.IISHost.Base/CommonService_W/getDataTableSQLResponse")]
        System.Threading.Tasks.Task<byte[]> getDataTableSQLAsync(byte[] loginTicket, string sql);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CommonService_WChannel : SG.Client.WCFIISHost.Base_CommonService_W.CommonService_W, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonService_WClient : System.ServiceModel.ClientBase<SG.Client.WCFIISHost.Base_CommonService_W.CommonService_W>, SG.Client.WCFIISHost.Base_CommonService_W.CommonService_W {
        
        public CommonService_WClient() {
        }
        
        public CommonService_WClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonService_WClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonService_WClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonService_WClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] GetSystemOrganization(byte[] validationTicket) {
            return base.Channel.GetSystemOrganization(validationTicket);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetSystemOrganizationAsync(byte[] validationTicket) {
            return base.Channel.GetSystemOrganizationAsync(validationTicket);
        }
        
        public byte[] GetSystemDataSet(byte[] validationTicket) {
            return base.Channel.GetSystemDataSet(validationTicket);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetSystemDataSetAsync(byte[] validationTicket) {
            return base.Channel.GetSystemDataSetAsync(validationTicket);
        }
        
        public byte[] GetSystemDataSetByOrg(byte[] validationTicket, string sOrgID) {
            return base.Channel.GetSystemDataSetByOrg(validationTicket, sOrgID);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetSystemDataSetByOrgAsync(byte[] validationTicket, string sOrgID) {
            return base.Channel.GetSystemDataSetByOrgAsync(validationTicket, sOrgID);
        }
        
        public byte[] SearchLog(byte[] loginTicket, string sFilter) {
            return base.Channel.SearchLog(loginTicket, sFilter);
        }
        
        public System.Threading.Tasks.Task<byte[]> SearchLogAsync(byte[] loginTicket, string sFilter) {
            return base.Channel.SearchLogAsync(loginTicket, sFilter);
        }
        
        public bool TestConnection(byte[] validationTicket) {
            return base.Channel.TestConnection(validationTicket);
        }
        
        public System.Threading.Tasks.Task<bool> TestConnectionAsync(byte[] validationTicket) {
            return base.Channel.TestConnectionAsync(validationTicket);
        }
        
        public bool TestConnectionD(byte[] validationTicket, string dbType, string Server, string database, string user, string password) {
            return base.Channel.TestConnectionD(validationTicket, dbType, Server, database, user, password);
        }
        
        public System.Threading.Tasks.Task<bool> TestConnectionDAsync(byte[] validationTicket, string dbType, string Server, string database, string user, string password) {
            return base.Channel.TestConnectionDAsync(validationTicket, dbType, Server, database, user, password);
        }
        
        public void WriteLogOP(byte[] loginTicket, string sFunID, string sFSubunID, string sFdesc, string sSql) {
            base.Channel.WriteLogOP(loginTicket, sFunID, sFSubunID, sFdesc, sSql);
        }
        
        public System.Threading.Tasks.Task WriteLogOPAsync(byte[] loginTicket, string sFunID, string sFSubunID, string sFdesc, string sSql) {
            return base.Channel.WriteLogOPAsync(loginTicket, sFunID, sFSubunID, sFdesc, sSql);
        }
        
        public byte[] GetModules(byte[] loginTicket) {
            return base.Channel.GetModules(loginTicket);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetModulesAsync(byte[] loginTicket) {
            return base.Channel.GetModulesAsync(loginTicket);
        }
        
        public void WriteLog(byte[] loginTicket, string logID, byte[] originalData, byte[] changes, string tableName, string keyFieldName, bool isMaster) {
            base.Channel.WriteLog(loginTicket, logID, originalData, changes, tableName, keyFieldName, isMaster);
        }
        
        public System.Threading.Tasks.Task WriteLogAsync(byte[] loginTicket, string logID, byte[] originalData, byte[] changes, string tableName, string keyFieldName, bool isMaster) {
            return base.Channel.WriteLogAsync(loginTicket, logID, originalData, changes, tableName, keyFieldName, isMaster);
        }
        
        public byte[] SearchLogData(byte[] loginTicket, string logUser, string tableName, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.SearchLogData(loginTicket, logUser, tableName, dateFrom, dateTo);
        }
        
        public System.Threading.Tasks.Task<byte[]> SearchLogDataAsync(byte[] loginTicket, string logUser, string tableName, System.DateTime dateFrom, System.DateTime dateTo) {
            return base.Channel.SearchLogDataAsync(loginTicket, logUser, tableName, dateFrom, dateTo);
        }
        
        public bool SaveFieldDef(byte[] loginTicket, byte[] data) {
            return base.Channel.SaveFieldDef(loginTicket, data);
        }
        
        public System.Threading.Tasks.Task<bool> SaveFieldDefAsync(byte[] loginTicket, byte[] data) {
            return base.Channel.SaveFieldDefAsync(loginTicket, data);
        }
        
        public byte[] GetLogFieldDef(byte[] loginTicket, string tableName) {
            return base.Channel.GetLogFieldDef(loginTicket, tableName);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetLogFieldDefAsync(byte[] loginTicket, string tableName) {
            return base.Channel.GetLogFieldDefAsync(loginTicket, tableName);
        }
        
        public string[] GetTracedFields(byte[] loginTicket, string tableName) {
            return base.Channel.GetTracedFields(loginTicket, tableName);
        }
        
        public System.Threading.Tasks.Task<string[]> GetTracedFieldsAsync(byte[] loginTicket, string tableName) {
            return base.Channel.GetTracedFieldsAsync(loginTicket, tableName);
        }
        
        public string C_GetTableID(byte[] loginTicket, string sTableName, string sFieldID) {
            return base.Channel.C_GetTableID(loginTicket, sTableName, sFieldID);
        }
        
        public System.Threading.Tasks.Task<string> C_GetTableIDAsync(byte[] loginTicket, string sTableName, string sFieldID) {
            return base.Channel.C_GetTableIDAsync(loginTicket, sTableName, sFieldID);
        }
        
        public string C_GetTableFieldValue(byte[] loginTicket, string sTableName, string sField, string SCon) {
            return base.Channel.C_GetTableFieldValue(loginTicket, sTableName, sField, SCon);
        }
        
        public System.Threading.Tasks.Task<string> C_GetTableFieldValueAsync(byte[] loginTicket, string sTableName, string sField, string SCon) {
            return base.Channel.C_GetTableFieldValueAsync(loginTicket, sTableName, sField, SCon);
        }
        
        public string GetSQLServerDbListString(byte[] validationTicket, string sServerName, string sUser, string sPwd) {
            return base.Channel.GetSQLServerDbListString(validationTicket, sServerName, sUser, sPwd);
        }
        
        public System.Threading.Tasks.Task<string> GetSQLServerDbListStringAsync(byte[] validationTicket, string sServerName, string sUser, string sPwd) {
            return base.Channel.GetSQLServerDbListStringAsync(validationTicket, sServerName, sUser, sPwd);
        }
        
        public byte[] GetDBLink(byte[] loginTicket) {
            return base.Channel.GetDBLink(loginTicket);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetDBLinkAsync(byte[] loginTicket) {
            return base.Channel.GetDBLinkAsync(loginTicket);
        }
        
        public byte[] GetDBLinkByID(byte[] loginTicket, string key) {
            return base.Channel.GetDBLinkByID(loginTicket, key);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetDBLinkByIDAsync(byte[] loginTicket, string key) {
            return base.Channel.GetDBLinkByIDAsync(loginTicket, key);
        }
        
        public byte[] G_GetSystemProfile(byte[] loginTicket) {
            return base.Channel.G_GetSystemProfile(loginTicket);
        }
        
        public System.Threading.Tasks.Task<byte[]> G_GetSystemProfileAsync(byte[] loginTicket) {
            return base.Channel.G_GetSystemProfileAsync(loginTicket);
        }
        
        public string G_GetSystemProfileVal(byte[] loginTicket, string key) {
            return base.Channel.G_GetSystemProfileVal(loginTicket, key);
        }
        
        public System.Threading.Tasks.Task<string> G_GetSystemProfileValAsync(byte[] loginTicket, string key) {
            return base.Channel.G_GetSystemProfileValAsync(loginTicket, key);
        }
        
        public byte[] GetAttachedFiles(byte[] loginTicket, string docID) {
            return base.Channel.GetAttachedFiles(loginTicket, docID);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetAttachedFilesAsync(byte[] loginTicket, string docID) {
            return base.Channel.GetAttachedFilesAsync(loginTicket, docID);
        }
        
        public byte[] getTable(byte[] loginTicket, string sTable) {
            return base.Channel.getTable(loginTicket, sTable);
        }
        
        public System.Threading.Tasks.Task<byte[]> getTableAsync(byte[] loginTicket, string sTable) {
            return base.Channel.getTableAsync(loginTicket, sTable);
        }
        
        public byte[] getField(byte[] loginTicket, string sTableName) {
            return base.Channel.getField(loginTicket, sTableName);
        }
        
        public System.Threading.Tasks.Task<byte[]> getFieldAsync(byte[] loginTicket, string sTableName) {
            return base.Channel.getFieldAsync(loginTicket, sTableName);
        }
        
        public byte[] getDataTableSQL(byte[] loginTicket, string sql) {
            return base.Channel.getDataTableSQL(loginTicket, sql);
        }
        
        public System.Threading.Tasks.Task<byte[]> getDataTableSQLAsync(byte[] loginTicket, string sql) {
            return base.Channel.getDataTableSQLAsync(loginTicket, sql);
        }
    }
}
